name: songeet
version: 1.4.0+4
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  audio_service: ^0.18.7
  audio_session: ^0.1.10
  avatar_glow: ^2.0.2
  cached_network_image: ^3.2.1
  collection: ^1.16.0
  cupertino_icons: ^1.0.2
  flutter: 
    sdk: flutter
  fluttertoast: ^8.0.9
  get_it: ^7.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  html: ^0.15.0
  http: ^0.13.5
  just_audio: ^0.9.28
  material_design_icons_flutter: ^5.0.6996
  on_audio_query: ^2.6.1
  package_info_plus: ^1.4.3+1
  path_provider: ^2.0.11
  receive_sharing_intent: ^1.4.5
  share_plus: ^4.0.10+1
  speech_to_text: ^5.6.1
  url_launcher: ^6.1.5
  youtube_explode_dart: ^1.12.0

dev_dependencies: 
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  hive_generator: ^1.1.3

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.png
  color_dark: "#000000"
  image_dark: assets/splash.png
  android_12:
    color: "#ffffff"
    image: assets/splash.png
    color_dark: "#000000"
    image_dark: assets/splash.png

flutter: 
  uses-material-design: true

  assets:
    - assets/

